/*
SQLyog Ultimate v13.1.2 (64 bit)
MySQL - 10.3.27-MariaDB-0+deb10u1 : Database - examen_desarrollo
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`examen_desarrollo` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci */;

USE `examen_desarrollo`;

/*Table structure for table `medicos` */

DROP TABLE IF EXISTS `medicos`;

CREATE TABLE `medicos` (
  `id_medico` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) COLLATE utf8_spanish_ci NOT NULL,
  PRIMARY KEY (`id_medico`)
) ENGINE=InnoDB AUTO_INCREMENT=128 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

/*Data for the table `medicos` */

insert  into `medicos`(`id_medico`,`nombre`) values 
(1,'MIGUEL ANGEL HERNANDEZ'),
(2,'VERONICA BARRIENTOS'),
(3,'JOSE LUIS ZUÑIGA'),
(4,'PAOLO NICOLAS RODRIGUEZ'),
(5,'EUDELIA BLANCAS'),
(6,'LUCILA MORALES'),
(7,'MA CELIA RAMOS'),
(8,'HILARIO OLMOS'),
(9,'ANAYELI GARCIA'),
(10,'ANA ELEUTERIA PALAFOX'),
(11,'SERGIO HERNANDEZ'),
(12,'SANTOS SANCHEZ'),
(13,'ALEJANDRO GUADALUPE MORALES'),
(14,'ANGEL GABRIEL  GUERRERO'),
(15,'MA. CECILIA AMELIA LOPEZ'),
(16,'EVA YEBRA'),
(17,'SANJUANA LOPEZ'),
(18,'DAVID ARENAS'),
(19,'LUZ MARCELA HERNANDEZ'),
(20,'MARIA DEL SOCORRO LOPEZ'),
(21,'ISAIAS GABRIEL SILVA'),
(22,'JUAN DIEGO OLMOS'),
(23,'JUAN JOSE GONZALEZ'),
(24,'INGRID MAGALI ESTRADA'),
(25,'EDITH ROSSANA ARELLANO'),
(26,'CLAUDIA BERENICE RODRIGUEZ'),
(27,'BRITTANY DENISSE OLMOS'),
(28,'LETICIA CABRERA'),
(29,'MA. JUDITH GRANADOS'),
(30,'JOSE ARENAS'),
(31,'JONATHAN ALAYN NAVARRO'),
(32,'PAMELA GUADALUPE DIAZ'),
(33,'MARIA RAMIREZ'),
(34,'OMAR ALEXIS ALCANTARA'),
(35,'SARA ISABEL AGUAYO'),
(36,'BRAYAN ALEXANDER HERNANDEZ '),
(37,'MARIA DE LOURDES GONZALEZ'),
(38,'AMELIA JIMENEZ'),
(39,'JOSE ALEJANDRO X'),
(40,'DANIEL FERNANDO PALACIOS'),
(41,'JOANA MONSERRAT TORRES'),
(42,'MA. LEONOR CARRTERO'),
(43,'JOSE  VENTURA GARNICA'),
(44,'GABRIEL ITIEL TORRES'),
(45,'DANNA CAMILA MAYORGA'),
(46,'MAYRA AGUILAR'),
(47,'ROBERTO  VILLANUEVA'),
(48,'SHALMA MARIA LOPEZ'),
(49,'MA. PAZ SANCHEZ'),
(50,'MATEO LONA'),
(51,'LUIS ROBERTO ROSAS'),
(52,'CINTYA MAITE VAZQUEZ'),
(53,'ESTEFANA ORTEGA'),
(54,'ANTONY PALOMA YEBRA'),
(55,'MARIA  VICTORIA GUERRERO'),
(56,'LAURA LIZETTE MORALES'),
(57,'SANTIAGO MARQUEZ'),
(58,'R.N TORRES'),
(59,'MODESTO ROCHA'),
(60,'MA. DE LA LUZ BIBIAN'),
(61,'GRACIELA RAMIREZ'),
(62,'EUSEBIO ARELLANO'),
(63,'R.N YEBRA'),
(64,'PATRICIA MONTIEL'),
(65,'AMALIA HERNANDEZ'),
(66,'CARLOS LOPEZ'),
(67,'BRENDA ALCANTARA'),
(68,'MARIA LUCINA ARREGUIN'),
(69,'MARCELA PALACIOS'),
(70,'ANGELA GUADALUPE MORALES'),
(71,'JOSE GPE. TAVARES'),
(72,'NERI MARIA ALVAREZ'),
(73,'DIEGO EMMANUEL SAUCEDO'),
(74,'OCTAVIO MORALES'),
(75,'IRMA BARRIENTOS'),
(76,'RAQUEL GARNICA'),
(77,'GLORIA RAMOS'),
(78,'MAYRA ROXANA CAUDILLO'),
(79,'M. BUENAVENTURA GUTIERREZ'),
(80,'MANUEL PONCE'),
(81,'LILIANA ELIZABETH MENDEZ'),
(82,'SANJUANA GUEVARA'),
(83,'JOSE LUIS RAMIREZ'),
(84,'MA CRUZ PEREZ'),
(85,'ELIAS RIVERA'),
(86,'NATALIA JUDITH MACIAS'),
(87,'LA LUISA RENDON'),
(88,'MARTHA LIZET LOPEZ'),
(89,'MARICELA CUEVAS'),
(90,'MITZILI AZUCENA JUAREZ'),
(91,'R.N. AGUILAR'),
(92,'CRISTIAN RAMIREZ'),
(93,'MA FELICITAS MARTINEZ'),
(94,'JUANA VALERIA HERRERA'),
(95,'MA. DEL CARMEN VAZQUEZ'),
(96,'MARIANO RAMIREZ'),
(97,'MARIA FERNANDA MUÑOZ'),
(98,'ALAN MARTINEZ'),
(99,'DIANA LAURA MARQUEZ'),
(100,'LIZETH ESTEFANA LOPEZ');

/*Table structure for table `pacientes` */

DROP TABLE IF EXISTS `pacientes`;

CREATE TABLE `pacientes` (
  `id_paciente` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) COLLATE utf8_spanish_ci NOT NULL,
  PRIMARY KEY (`id_paciente`)
) ENGINE=InnoDB AUTO_INCREMENT=128 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

/*Data for the table `pacientes` */

insert  into `pacientes`(`id_paciente`,`nombre`) values 
(1,'GUADALUPE MEZA'),
(2,'CARLOS VALLEJO'),
(3,'ANA LILIA VERGARA'),
(4,'JULIETA BECERRA'),
(5,'KENNETH LOZANO'),
(6,'BRITANY MELANI ARREDONDO'),
(7,'BRISIA GERALDINE BARRIENTOS'),
(8,'MARIA EVA  GUERRA'),
(9,'RN ROJAS'),
(10,'BLANCA GUADALUPE RODRIGUEZ'),
(11,'SUSANA GUTIERREZ'),
(12,'MARIA SOLEDAD MORALES'),
(13,'FEDERICO MENDOZA'),
(14,'MA. GUADALUPE FUNES'),
(15,'FERNANDO RODRIGO RAMIREZ'),
(16,'MIGUEL ANGEL GARCIA'),
(17,'VIOLETA DANAE GUERRA'),
(18,'LUIS MANUEL SEGOVIANO'),
(19,'MARIA ISABEL VELAZQUEZ'),
(20,'HECTOR JUAREZ'),
(21,'XIMENA GONZALEZ'),
(22,'REYNA AYALA'),
(23,'AXEL GAEL VERA'),
(24,'ANGEL LEONARDO PASTRANO'),
(25,'MARIA BERENICE HURTADO'),
(26,'NORMA ANGELICA VALTIERRA'),
(27,'LUIS ANGEL ORTEGA'),
(28,'JOSE ALONSO MENDIOLA '),
(29,'ALAN DAVID LOPEZ'),
(30,'JOSE MANUEL HERNANDEZ'),
(31,'TORIBIO QUINTERO'),
(32,'JOSE LUIS GARCIA'),
(33,'LIZBETH JANET GODINEZ'),
(34,'DARIAN JUDITH AGUAYO'),
(35,'MARIO EFRAIN LOPEZ'),
(36,'KAREN IVETTE PALAFOX'),
(37,'MA. GUADALUPE  MEDRANO'),
(38,'LILIANA JACQUELINE MANZANO'),
(39,'EUTIQUIO ORTEGA'),
(40,'FRANCISCA NIETO'),
(41,'MA. CONCEPCION SANCHEZ'),
(42,'NORMA RAMIREZ'),
(43,'ERIKA REA'),
(44,'MARAI ELENA GONZALEZ'),
(45,'JULIO CESAR MARTINEZ'),
(46,'JOSE INOCENTE MARTINEZ'),
(47,'MARIA GUADALUPE SERNA'),
(48,'AGUEDA YATZIL ORDAZ'),
(49,'MA ISABEL VAZQUEZ'),
(50,'PERLA YOSELIN NIEVES'),
(51,'IMELDA GALVAN'),
(52,'ARMANDO LOPEZ'),
(53,'VERONICA MORAN'),
(54,'SANDRA VERONICA LIRA'),
(55,'ISIDRO MURRIETA'),
(56,'ANTONIO GONZALEZ'),
(57,'MANUELA MURRIETA'),
(58,'LAURA LUCERO RAMIREZ'),
(59,'MARCOS MORALES'),
(60,'MARINA SILVA'),
(61,'FLOR ESPERANZA LORIA'),
(62,'ANGEL MARTINEZ'),
(63,'ALMA MELISA LOPEZ'),
(64,'MA. GUADALUPE MOSQUEDA'),
(65,'ANA PATRICIA GAMEZ'),
(66,'YESSICA LOAIZA'),
(67,'HANA SAYURI HERNANDEZ'),
(68,'PATRICIA ESPARZA'),
(69,'RN HERNANDEZ'),
(70,'IVONNE NAYELI IBARRA'),
(71,'ANA PAULINA MOYA'),
(72,'JUDITH OLMOS'),
(73,'MANUEL SANCHEZ'),
(74,'CONSTANTINO RAMIREZ'),
(75,'DAMARIS FABIOLA SALAZAR'),
(76,'RAFAEL CASTILLO'),
(77,'LEONEL RICARDO TORRES'),
(78,'OSCAR  ARTURO MARTINEZ'),
(79,'YARA DOLORES CHAVEZ'),
(80,'ADRIANA SALAS'),
(81,'MARIA DOLORES JANTES'),
(82,'ANGELICA MARVILA JUAREZ'),
(83,'MARTHA TERESA AGUILAR'),
(84,'JAASAI BANI PALACIOS'),
(85,'RAQUEL AGUILERA'),
(86,'ARIADNA MELANI SEGAVIANO'),
(87,'JUANA PALAFOX'),
(88,'IMELDA MARCELA GUTIERREZ'),
(89,'VICTORIA BERENICE ARIAS'),
(90,'MA GUADALUPE RAMIREZ'),
(91,'AMPARO GOMEZ'),
(92,'MARTHA VALDEZ'),
(93,'YOLTZIN LONA'),
(94,'LAURA MARTINEZ'),
(95,'MARGARITA OLMOS'),
(96,'MARIA DE LOS ANGELES IBARRA'),
(97,'VICTOR HUGO ALVAREZ'),
(98,'GREGORIO SANTANA'),
(99,'SANJUANA BAEZ'),
(100,'MA. GUADALUPE VAZQUEZ');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;



-- newww


CREATE TABLE `consulta` (
  `id_consulta` int(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `id_medico` int  NOT NULL,
  `id_paciente` int  NOT NULL,
  `id_diagnostico` int  NOT NULL,
  `tratamiento` varchar(250) COLLATE utf8_spanish_ci NULL,
  `costo` float(11)  default NULL,
  PRIMARY KEY (`id_consulta`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


ALTER TABLE `consulta`
  ADD CONSTRAINT `consulta_ibfk_1` FOREIGN KEY (`id_medico`) REFERENCES `medicos` (`id_medico`) ON UPDATE CASCADE,
  ADD CONSTRAINT `consulta_ibfk_2` FOREIGN KEY (`id_paciente`) REFERENCES `pacientes` (`id_paciente`) ON UPDATE CASCADE,
  ADD CONSTRAINT `consulta_ibfk_3` FOREIGN KEY (`id_diagnostico`) REFERENCES `diagnosticos` (`id_diagnostico`) ON UPDATE CASCADE;

CREATE PROCEDURE `PA_REGISTRARMEDICO` 
(IN `nombre` VARCHAR(80), IN `cedula` VARCHAR(10)) 
BEGIN INSERT INTO `medicos`( `nombre`, `cedula`) VALUES (nombre,cedula); END;;

DELIMITER //
CREATE PROCEDURE `PA_REGISTRARPACIENTES`(
    IN `nombre` VARCHAR(100), 
    IN `curp` VARCHAR(18)
)
    NOT DETERMINISTIC 
    CONTAINS SQL 
    SQL SECURITY DEFINER
BEGIN
    INSERT INTO `pacientes`(`nombre`, `curp`) 
    VALUES (nombre, curp);
END//

DELIMITER ;



-- JOIN CONSULTAS


SELECT consulta.id_consulta, consulta.tratamiento, consulta.fecha,consulta.costo, 
pacientes.nombre, pacientes.curp, medicos.nombre, medicos.cedula,
diagnosticos.nombre
FROM consulta
INNER JOIN medicos ON consulta.id_medico = medicos.id_medico
INNER JOIN pacientes ON consulta.id_paciente = pacientes.id_paciente
INNER JOIN diagnosticos ON consulta.id_diagnostico = diagnosticos.id_diagnostico 
WHERE consulta.tratamiento
LIKE '".$valor."%' ORDER BY consulta.id_consulta DESC LIMIT $inicio,$limite


DELIMITER //
CREATE PROCEDURE `PA_REGISTRARCONSULTA`(
    IN `fecha` DATE,
    IN `id_medico` INT,
    IN `id_paciente` INT,
    IN `id_diagnostico` INT,
    IN `tratamiento` varchar(250),
    IN `costo` float(11)
)
    NOT DETERMINISTIC 
    CONTAINS SQL 
    SQL SECURITY DEFINER
BEGIN
    INSERT INTO `consulta`(`fecha`, `id_medico`, `id_paciente`, `id_diagnostico`, `tratamiento`, `costo`)
    VALUES (fecha, id_medico, id_paciente, id_diagnostico, tratamiento, costo);
END//

DELIMITER ;



SELECT consulta.fecha, COUNT(id_consulta) as totalConsultas, SUM(costo) as totalCosto,medicos.nombre as medico
FROM consulta INNER JOIN medicos ON consulta.id_medico = medicos.id_medico INNER JOIN pacientes ON consulta.id_paciente = pacientes.id_paciente
INNER JOIN diagnosticos ON consulta.id_diagnostico = diagnosticos.id_diagnostico
GROUP BY consulta.fecha, medicos.id_medico;

